# 第三章作业

## 一、

问题：在一个10类的模式识别问题中，有3类单独满足多类情况1，其余的类别满足多类情况2。问该模式识别问题所需判别函数的最少数目是多少？

答：最小判别函数数目为 3 + 7 * ( 7 - 1 ) / 2 + 1 = 25，即用一个判别函数分开多类情况1和多类情况2，再对每个多类情况应用对应的判别函数分开。

## 二、

问题：一个三类问题，其判别函数：d1(x)=-x1, d2(x)=x1+x2-1, d3(x)=x1-x2-1
1. 设这些函数是在多类情况1条件下确定的，绘出其判别界面和每一个模式类别的区域。
2. 设为多类情况2，并使：d12(x)= d1(x), d13(x)= d2(x), d23(x)= d3(x)。绘出其判别界面和多类情况2的区域。
3. 设d1(x), d2(x)和d3(x)是在多类情况3的条件下确定的，绘出其判别界面和每类的区域。

In [1]:
# 2-1
import matplotlib.pyplot as plt
import numpy as np

# d1: x1 = 0
x1 = np.zeros(20)
d1_x2 = np.arange(-10, 10)
plt.plot(x1, d1_x2, color='red', label='d1')

# d2: x2 = 1 - x1
x1 = np.arange(-10, 10)
d2_x2 = 1 - x1
plt.plot(x1, d2_x2, color='green', label='d2')

# d3: x2 = x1 - 1
x1 = np.arange(-10, 10)
d3_x2 = x1 - 1
plt.plot(x1, d3_x2, color='blue', label='d3')

plt.xlabel('x1')
plt.ylabel('x2')

plt.fill_between(x1, d3_x2, d2_x2, where=(x1<=0), facecolor="red", label="w1")

plt.fill_between(x1, d2_x2, 10, where=(x1>=0) & (x1<=1), facecolor="green", label="w2")
plt.fill_between(x1, d3_x2, 10, where=(x1>=1), facecolor="green")

plt.fill_between(x1, -10, d3_x2, where=(x1>=0) & (x1<=1), facecolor="blue", label="w3")
plt.fill_between(x1, -10, d2_x2, where=(x1>=1), facecolor="blue")

plt.legend()
plt.title('2-1 多类情况1')
plt.show()

# 2-2

# d12: x1 = 0
x1 = np.zeros(20)
d1_x2 = np.arange(-10, 10)
plt.plot(x1, d1_x2, color='red', label='d12')

# d13: x2 = 1 - x1
x1 = np.arange(-10, 10)
d2_x2 = 1 - x1
plt.plot(x1, d2_x2, color='green', label='d13')

# d23: x2 = x1 - 1
x1 = np.arange(-10, 10)
d3_x2 = x1 - 1
plt.plot(x1, d3_x2, color='blue', label='d23')

plt.xlabel('x1')
plt.ylabel('x2')

# w1: d12>0,d13>0
plt.fill_between(x1, d2_x2, 10, where=(x1>=0), facecolor="red", label="w1")

# w2: d21>0 => d12<0,d23>0
plt.fill_between(x1, d3_x2, 10, where=(x1<=0), facecolor="green", label="w2")

# w3: d31>0, d32>0 => d13<0,d23<0
plt.fill_between(x1, -11, d3_x2, where=(x1<=1), facecolor="blue", label="w3")
plt.fill_between(x1, -11, d2_x2, where=(x1>=1), facecolor="blue", label="w3")

plt.legend()
plt.title('2-2 多类情况2')
plt.show()

# 2-3

# d1: x1 = 0
x1 = np.zeros(20)
d1_x2 = np.arange(-10, 10)
plt.plot(x1, d1_x2, color='red', label='d1')

# d2: x2 = 1 - x1
x1 = np.arange(-10, 10)
d2_x2 = 1 - x1
plt.plot(x1, d2_x2, color='green', label='d2')

# d3: x2 = x1 - 1
x1 = np.arange(-10, 10)
d3_x2 = x1 - 1
plt.plot(x1, d3_x2, color='blue', label='d3')

plt.xlabel('x1')
plt.ylabel('x2')
x1 = np.arange(-10, 10, 0.2)

# w1: d1 > d2, d1 > d3
# -x1 > x1 + x2 - 1 => x2 < -2x1 + 1
# -x1 > x1 - x2 -1 => x2 > 2x1 - 1
plt.fill_between(x1, 2 * x1 - 1, -2 * x1 + 1, where=(x1<=0.5), facecolor="red", label="w1")

# w2: d2 > d1, d2 > d3
# x1 + x2 - 1 > -x1 => x2 > -2x1 + 1
# x1 + x2 - 1 > x1 - x2 -1 => x2 > 0
plt.fill_between(x1, -2 * x1 + 1, 21, where=(x1<0.6), facecolor="green", label="w2")
plt.fill_between(x1, 0, 21, where=(x1>=0.5), facecolor="green", label="w2")

# w3: x2 < 2 * x1 - 1, x2 < 0
plt.fill_between(x1, -21, 2 * x1 - 1, where=(x1<0.6), facecolor="blue", label="w1")
plt.fill_between(x1, -21, 0, where=(x1>=0.5), facecolor="blue", label="w1")

plt.legend()
plt.title('2-3 多类情况3')
plt.show()

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

## 三、

问题：两类模式，每类包括5个3维不同的模式，且良好分布。
1. 如果它们是线性可分的，问权向量至少需要几个系数分量？
2. 假如要建立二次的多项式判别函数，又至少需要几个系数分量？（设模式的良好分布不因模式变化而改变。）

答：
1. 
2. 

## 四、

问题：感知器算法求下列模式分类的解向量w:
- ω1: [[0, 0, 0], [1, 0, 0], [1, 0, 1], [1, 1, 0]]
- ω2: [[0, 0, 1], [0, 1, 1], [0, 1, 0], [1, 1, 1]]

In [2]:
w1 = [[0, 0, 0], [1, 0, 0], [1, 0, 1], [1, 1, 0]]
w1 = np.array(w1)
w1 = w1.T

w2 = [[0, 0, 1], [0, 1, 1], [0, 1, 0], [1, 1, 1]]
w2 = np.array(w2)
w2 = w2.T

In [3]:
tmp = np.ones((1, 4))

w1 = np.concatenate((w1, tmp), axis=0)
w2 = np.concatenate((w2, tmp), axis=0)
w2 = w2 * -1
print(w1)
print(w2)
w = np.concatenate((w1, w2), axis=1)
print(w)

[[0. 1. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 1. 1. 1.]]
[[-0. -0. -0. -1.]
 [-0. -1. -1. -1.]
 [-1. -1. -0. -1.]
 [-1. -1. -1. -1.]]
[[ 0.  1.  1.  1. -0. -0. -0. -1.]
 [ 0.  0.  0.  1. -0. -1. -1. -1.]
 [ 0.  0.  1.  0. -1. -1. -0. -1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.]]


In [4]:
# 解向量设为a
# 初始化解向量
# 取C = 1
a = np.array([[0, 0, 0, 0]])
while True:
    # 初始化标志位
    flag = True
    for _ in range(8):
        if np.dot(a, w[:, _].reshape([4, 1]))[0, 0] > 0:
            a = a
            flag = flag and True
        else:
            a = a + w[:, _].reshape([1, 4])
            flag = flag and False
    
    if flag:
        break

print(a)

[[ 2. -2. -2.  1.]]


- 所以解向量为 ( 2 -2 -2 1 )
- 判别函数为：d(x) = 2x1 - 2x2 - 2x3 + 1
